db/migrate/20191111070210_explorers_profile_listings.rb
=> Welcome page

db/migrate/20191111065137_create_traits.rb, db/schema.rb
Some small changes to migration tables. No dashboard additions yet.
=> Explorer dashboard

app/assets/stylesheets/application.css, app/views/landings/welcome.html.erb
Updated the welcome-page with interests.
=> added the row with interests hashtags

app/views/employers_profiles/show.html.erb
=> Employer dashboard

db/seeds.rb
=> SEED TABLE

app/views/employers/registrations/new.html.erb, app/views/employers/sessions/new.html.erb, app/views/explorers/registrations/new.html.erb, app/views/explorers/sessions/new.html.erb
Layout for login forms for employers and explorers.
=> styled the login forms

app/controllers/listings_controller.rb, app/views/employers_profiles/show.html.erb, app/views/layouts/application.html.erb, app/views/listings/index.html.erb
Dropdown menus for search, and link to individual post on the post index
=> Login forms

app/assets/stylesheets/application.css, app/views/employers/registrations/new.html.erb, app/views/explorers/registrations/new.html.erb, app/views/listings/index.html.erb, app/views/listings/new.html.erb, app/views/listings/show.html.erb, app/views/searches/show.html.erb
Initial style for a single listing, minor layout changes to the new listing form, and lowered the font of the registration forms title.
=> styled the single listing page and minor changes to listing form

app/assets/stylesheets/application.css, app/views/employers/sessions/new.html.erb, app/views/explorers/registrations/new.html.erb, app/views/explorers/sessions/new.html.erb
added links on login forms to redirect new users to register forms
=> Edited Login forms

app/views/employers_profiles/show.html.erb, app/views/layouts/application.html.erb
Changing links from navbars to point to the right pages
=> Fixing links

app/controllers/employers_profiles_controller.rb, app/views/employers_profiles/edit.html.erb, app/views/explorers_profiles/edit.html.erb
Added the Edit and Update page and function for Employers
=> Employers profiles edit

app/controllers/explorers_profiles_controller.rb, app/controllers/listings_controller.rb, app/models/explorers_profile.rb, app/models/listing.rb, db/migrate/20191111070210_explorers_profiles_listings.rb, db/schema.rb
Explorer can see employer, employer can see explorer. done. need some restrictions, which will implement now
=> Explorer see employer

app/controllers/employers_profiles_controller.rb, app/views/employers_profiles/new.html.erb
=> Cloudinary

app/controllers/explorers/registrations_controller.rb, app/controllers/explorers_profiles_controller.rb, app/views/employers_profiles/new.html.erb, app/views/explorers_profiles/new.html.erb, app/views/layouts/application.html.erb
cloudinary works for employer and explorer sign-up
=> Test cloudinary

app/assets/stylesheets/application.css, app/assets/stylesheets/scaffolds.scss, app/controllers/listings_controller.rb, app/views/explorers_profiles/show.html.erb, app/views/layouts/application.html.erb, app/views/listings/connect.html.erb, app/views/listings/index.html.erb, app/views/listings/new.html.erb
Styled the different navbars for employers, explorers and not logged in details. 
Moved the basic search to the navbar for explorers.
Moved the advanced search into the search by dropdown.
Styling details for the listings page and the dropdownn search section.
Added profile photo on explorers profile dashboard.
=> Search in navbar, navbar details, advanced search moved to dropdown

config/locales/devise.en.yml
"Signed in successfully" message removed
=> Checking flow

Gemfile, Gemfile.lock, app/controllers/listings_controller.rb, app/views/listings/connect.html.erb, app/views/listings/show.html.erb
Listing can see applicants immediately. no need to click on 'see applicants'
=> Listing see applicants

app/assets/stylesheets/application.css, app/controllers/listings_controller.rb, app/views/employers_profiles/show.html.erb, app/views/listings/edit.html.erb, app/views/listings/show.html.erb
Changed the form for editing the listing, to have the industries, traits and environments forms to update.
Changed the Company profile dashboard, to show the company logo and greet the current company. Styled the background.
Moved the interested applicants grid, to the individual company listing page, and styled in smaller cards.
=> Edit listing page; Company profile page; Interested applicant feature.

app/views/listings/index.html.erb
Added the date posted for each listing
=> Added Posted Date

app/assets/stylesheets/application.css, app/controllers/employers_profiles_controller.rb, app/views/employers_profiles/show.html.erb, app/views/explorers_profiles/show.html.erb, app/views/landings/landing.html.erb, app/views/listings/index.html.erb, app/views/listings/new.html.erb
Created a dashboard with navigation panel for explorer if they don't have any listings yet, to be redirected there when creating a new profile instead of the form for a new listing.
Organized all checkboxes in columns.
=> Dropdown alignment, changed flow when company sign up
